#!/usr/bin/env python3
import argparse
import csv
import math
import re
import subprocess
from pathlib import Path


VARS = ["rho", "momx", "momy", "E"]


def latest_plot(raw_dir: Path, prefix: str) -> Path:
    cands = []
    for p in raw_dir.glob(prefix + "*"):
        suffix = p.name[len(prefix) :]
        if suffix.isdigit():
            cands.append((int(suffix), p))
    if not cands:
        raise FileNotFoundError(f"No plotfiles found for prefix: {prefix}")
    cands.sort()
    return cands[-1][1]


def run_fcompare(fcompare_exe: Path, norm: int, ref_plot: Path, soln_plot: Path):
    cmd = [str(fcompare_exe), "-n", str(norm), str(ref_plot), str(soln_plot)]
    proc = subprocess.run(cmd, text=True, capture_output=True, check=False)
    txt = proc.stdout
    if proc.returncode not in (0, 1):
        raise RuntimeError(
            f"fcompare failed with code {proc.returncode}:\n{proc.stderr}\n{txt}"
        )
    errors = {}
    for raw in txt.splitlines():
        parts = raw.strip().split()
        if len(parts) >= 2 and parts[0] in VARS:
            errors[parts[0]] = float(parts[1])
    missing = [v for v in VARS if v not in errors]
    if missing:
        raise RuntimeError(f"Could not parse variables {missing} from fcompare output:\n{txt}")
    return errors


def parse_runtime(log_path: Path):
    text = log_path.read_text()
    match = re.search(r"Run time =\s*([0-9.eE+-]+)", text)
    return float(match.group(1)) if match else math.nan


def add_orders(rows, key):
    rows = sorted(rows, key=lambda r: r["N"])
    prev = None
    for row in rows:
        row[f"order_{key}"] = ""
        if prev is not None:
            ecoarse = float(prev[key])
            efine = float(row[key])
            if efine > 0.0:
                row[f"order_{key}"] = f"{math.log(ecoarse / efine, 2.0):.3f}"
        prev = row
    return rows


def write_markdown(md_path: Path, rows):
    lines = []
    lines.append("# Smooth Entropy-Wave Convergence")
    lines.append("")
    lines.append(
        "The test uses a localized Gaussian entropy perturbation advected at constant velocity."
    )
    lines.append(
        "For each grid, the numerical final plotfile is compared against an exact shifted-reference plotfile generated by the same driver at $t=0$ on the same mesh."
    )
    lines.append("")
    lines.append("| N | dx | L1(rho) | order | L2(rho) | order | runtime (s) |")
    lines.append("|---:|---:|---:|---:|---:|---:|---:|")
    for row in rows:
        lines.append(
            f"| {row['N']} | {float(row['dx']):.6f} | {float(row['L1_rho']):.6e} | "
            f"{row['order_L1_rho'] or '--'} | {float(row['L2_rho']):.6e} | "
            f"{row['order_L2_rho'] or '--'} | {float(row['runtime_s']):.3f} |"
        )
    md_path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description="Summarize smooth entropy-wave convergence runs.")
    ap.add_argument("--results-dir", required=True)
    ap.add_argument("--fcompare-exe", required=True)
    args = ap.parse_args()

    results_dir = Path(args.results_dir).resolve()
    raw_dir = results_dir / "raw"
    log_dir = results_dir / "logs"
    checks_dir = results_dir / "checks"
    checks_dir.mkdir(parents=True, exist_ok=True)
    fcompare_exe = Path(args.fcompare_exe).resolve()

    rows = []
    for n in [128, 256, 512]:
        ref_plot = raw_dir / f"plt_smooth_ref_n{n}00000"
        soln_plot = latest_plot(raw_dir, f"plt_smooth_num_n{n}")
        l1 = run_fcompare(fcompare_exe, 1, ref_plot, soln_plot)
        l2 = run_fcompare(fcompare_exe, 2, ref_plot, soln_plot)
        rows.append(
            {
                "N": n,
                "dx": 1.0 / n,
                "runtime_s": parse_runtime(log_dir / f"smooth_num_n{n}.log"),
                "L1_rho": l1["rho"],
                "L2_rho": l2["rho"],
                "L1_momx": l1["momx"],
                "L2_momx": l2["momx"],
                "L1_momy": l1["momy"],
                "L2_momy": l2["momy"],
                "L1_E": l1["E"],
                "L2_E": l2["E"],
            }
        )

    rows = add_orders(rows, "L1_rho")
    rows = add_orders(rows, "L2_rho")

    csv_path = checks_dir / "smooth_entropy_convergence.csv"
    with csv_path.open("w", newline="") as f:
        fieldnames = [
            "N",
            "dx",
            "runtime_s",
            "L1_rho",
            "order_L1_rho",
            "L2_rho",
            "order_L2_rho",
            "L1_momx",
            "L2_momx",
            "L1_momy",
            "L2_momy",
            "L1_E",
            "L2_E",
        ]
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for row in rows:
            w.writerow(row)

    write_markdown(checks_dir / "smooth_entropy_convergence.md", rows)
    print(f"CSV={csv_path}")
    print(f"MD={checks_dir / 'smooth_entropy_convergence.md'}")


if __name__ == "__main__":
    main()
